---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: check-executables-have-shebangs
      # - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      # - id: detect-aws-credentials
  # CICD ####################################################################
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.1
    hooks:
      - id: check-github-workflows
  # ANSIBLE ####################################################################
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.22.0
    hooks:
      - id: ansible-lint
        args: ['-c', '.ci/ansible-lint']
  # DOCS #######################################################################
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint_docker
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--config', '.ci/flake8']
  # DATA FILES #################################################################
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: ['-c=.ci/yamllint']
  # TERRAFORM ##################################################################
  - repo: https://github.com/tfsec/tfsec
    rev: v1.28.4
    hooks:
      - id: tfsec
        args: ["--tfvars-file", "terraform/terraform.tfvars"]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
  # COMMITIZEN #################################################################
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
