---
# Update system
- name: System Info [Common]
  debug:
    msg:
    - "ip": "{{ ansible_default_ipv4.address }}"
    - "Host": "{{ ansible_nodename }}"
    - "OS": "{{ ansible_os_family }}"
    - "memory":  "{{ ansible_memtotal_mb }}"
    - "vCPU": "{{ ansible_processor_vcpus }}"
    - "Distribution": "{{ ansible_distribution }}"
    - "interfaces": "{{ ansible_facts.interfaces }}"
  tags:
    - update_system

- name: Find network interface name with public IP
  set_fact:
    internet_iface: "{{ item }}"
  when: hostvars[inventory_hostname]['ansible_%s' | format(item) ]['ipv4']['address'] == ansible_default_ipv4.address
  with_items:
    - "{{ ansible_interfaces }}"

- name: Update system cache if OS is Debian
  include_tasks: update_ubuntu.yaml
  tags:
    - update_system
  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")

- name: Update system cache if OS is RedHat
  include_tasks: update_centos.yaml
  tags:
    - update_system
  when: (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "RedHat")
