---

# Install WireGuard
- name: In WG config we will use net interface
  debug:
    msg:
      - "We will use network interface: {{ internet_iface }}-{{ ansible_default_ipv4.address}}"
      - "We will use network port: {{ wg_port }}"
      - "WG Subnet will be:  {{ adress_subnet }}"
      - "Server  subnet ip will be : {{ adress_srv }}"
      - "Peer subnet ip will be : {{ adress_peer }}"

- name: Install WireGuard and resolvconf [REMOTE SERVER]
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - wireguard
    - resolvconf
  tags:
    - install_wireguard

### Remove old configs #####
- name: Make sure that service WG is stopped [REMOTE SERVER]
  systemd:
    name: wg-quick@wg0.service
    state: stopped

- name: Search old configs [REMOTE SERVER]
  find:
    path: /etc/wireguard
    file_type: any
  register: old_conf

- name: Delete old configs [REMOTE SERVER]
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_conf.files }}"

- name: Search old configs [LOCAL]
  find:
    path: /etc/wireguard
    file_type: any
  register: old_conf_loc
  delegate_to: 127.0.0.1

- name: Delete old configs [LOCAL]
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_conf_loc.files }}"
  delegate_to: 127.0.0.1

##### Generating  server keys #####
- name: Generate WireGuard private server key [REMOTE SERVER]
  command: wg genkey
  register: out_pvkey

- name: Save private key [REMOTE SERVER]
  lineinfile:
    path: /etc/wireguard/private.key
    line: "{{ out_pvkey.stdout }}"
    create: yes

- name: Change permission for key [REMOTE SERVER]
  file:
    path: /etc/wireguard/private.key
    owner: root
    group: root
    mode: '0600'

- name: Generate WireGuard public server key [REMOTE SERVER]
  shell: 'echo "{{ out_pvkey.stdout }}" | wg pubkey'
  register: out_pubkey

- name: Save pubkey key
  lineinfile:
    path: /etc/wireguard/public.key
    line: "{{ out_pubkey.stdout }}"
    create: yes

- name: Read private server key [REMOTE SERVER]
  slurp:
    src: /etc/wireguard/private.key
  register: pv_key_enc

- name: Read pub server key [REMOTE SERVER]
  slurp:
    src: /etc/wireguard/public.key
  register: pub_key_enc

- name: Decode private server key
  set_fact:
    pv_key: "{{ pv_key_enc.content | b64decode }}"
- name: Decode pub server key
  set_fact:
    pub_key: "{{ pub_key_enc.content | b64decode }}"


### Generate local peer keys #####
- name: Generate WireGuard private peer key [LOCAL]
  command: wg genkey
  delegate_to: 127.0.0.1
  register: out_pvkey_local
  tags:
    - local_peer

- name: Generate WireGuard public server key [LOCAL]
  shell: echo "{{ out_pvkey_local.stdout }}"| wg pubkey
  delegate_to: 127.0.0.1
  register: out_pubkey_local
  tags:
    - local_peer

- name: Save pubkey key [LOCAL]
  become: true
  become_user: root
  lineinfile:
    path: /etc/wireguard/public.key
    line: "{{ out_pubkey_local.stdout }}"
    create: yes
  delegate_to: 127.0.0.1

#- name: Read local peer pv key [LOCAL]
#  set_fact:
#    pv_peer_key: "{{ lookup('file','/etc/wireguard/private.key') }}"

- name: Read local peer pub key [LOCAL]
  set_fact:
    pub_peer_key: "{{ out_pubkey_local.stdout }}"

#### Render configs #####
- name: Create WireGuard  server config file [REMOTE SERVER]
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    mode: '0600'
  tags:
    - config

- name: Create WireGuard  peer config file [LOCAL]
  template:
    src: wg_peer.j2
    dest: ./wg_peer.conf
  delegate_to: 127.0.0.1
  register: local_conf_path
  tags:
    - config

- name: Adjust sysctl.config [REMOTE SERVER]
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  tags:
    - config

#### Setup UFW #####
- name: Allow SSH port [REMOTE SERVER]
  community.general.ufw:
    rule: allow
    port: '22'
  tags:
    - config

- name: Allow UDP WireGuard port [REMOTE SERVER]
  community.general.ufw:
    rule: allow
    port: "{{ wg_port }}"
  tags:
    - config

- name: Allow HTTP(s)/DNS ports [REMOTE SERVER]
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - '53'
    - '80'
    - '443'
  tags:
    - config

- name: Enable Deny policy and enable UFW [REMOTE SERVER]
  community.general.ufw:
    state: enabled
    policy: deny
    logging: 'on'
  tags:
    - config

- name: Up interface [REMOTE SERVER]
  shell: wg-quick up /etc/wireguard/wg0.conf

#- name: Enable WireGuard
#  systemd:
#    name: wg-quick@wg0.service
#    state: started
#    enabled: yes
#  tags:
#    - config

- name: Activating peer on the server side [REMOTE SERVER]
  command: sudo wg set wg0 peer "{{ pub_peer_key }}" allowed-ips "{{ adress_peer }}"
  tags:
    - config

- name: Path to local config
  debug:
    msg: "{{ local_conf_path.dest}}"
