---
# handlers file for wg_install
- name: Restart WG
  systemd:
    name: wg-quick@wg0.service
    state: restarted

- name: Enable Firewalld
  systemd:
    name: firewalld
    state: started
    enabled: true

- name: Reload Firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Reload UFW
  systemd:
    name: ufw
    state: reloaded
