---
- name: "Wait SSH"
  hosts: all
  gather_facts: true
  tasks:
    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      become: false
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 1
        timeout: 300
      vars:
        ansible_connection: local

- name: "Install WireGuard"
  hosts: all
  gather_facts: true
  become: true
  roles:
    - update_system
    - wg_install
